### ISSUE TITLE
Problems with epsilon (and possibly more)

### ISSUE THREAD

**Issue by freron** [camoy/amath#12]
It appears there are problems with at least one greek letter (I haven't looked for such issues in general):

```
printf "epsilon" | ./amath 
<math><mi>&epsi;</mi><mi>l</mi><mi>o</mi><mi>n</mi></math>
```

Two problems:
- It appears that `amath` expects `epsi` to be used instead of `epsilon`.
- It generates `&epsi;`, but the correct entity is `&epsilon;`.

Thanks for creating this tool.

**Comment by aslakr** [comment]
both are correct according to http://www.w3.org/2003/entities/2007/htmlmathml-f.ent

``` xml
<!ENTITY epsi             "&#x003B5;" ><!--GREEK SMALL LETTER EPSILON -->
<!ENTITY epsilon          "&#x003B5;" ><!--GREEK SMALL LETTER EPSILON -->
```

`ASCIIMathML.js` support both (from TeX?) https://github.com/asciimath/asciimathml/blob/master/ASCIIMathML.js#L222

``` js
{input:"epsi",   tag:"mi", output:"\u03B5", tex:"epsilon", ttype:CONST},
```

but  http://asciimath.org only list `epsilon` as an example.

**Comment by camoy** [comment]
It should work with both `epsi` and `epsilon` now. I believe this is the only instance of the problem, but let me know if there are any more. Thanks for calling attention to this.

**Comment by freron** [comment]
Great! (I had not considered the, somewhat silly, possibility that `epsi` was also legal. Sorry about that.)

**Comment by aslakr** [comment]
as a reference http://www.w3.org/TR/xml-entity-names/#epsilon

> Historically there has been much confusion and lack of agreement over variant forms for lower case epsilon.
> 
> This specification uses the definitions below. Note that the name **epsilon** is used for the character used in textual Greek (U+03B5) and **varepsilon** used for the epsilon symbol character more commonly used in mathematics (U+03F5). Note that this usage is compatible with the naming of similar pairs of characters (for example **theta**, **vartheta**) but _incompatible_ with the naming convention used in TeX, MathML2 and some earlier mappings of the ISO entity sets to Unicode.

**Comment by freron** [comment]
What a mess. Just for the record, I would prefer if only reserved characters used entities. The rest could just be UTF-8. The future is here :-)

**Comment by camoy** [comment]
The only reason I chose entities is because `ASCIIMathML.js` uses them. I suppose unicode characters make more sense though.

**Comment by aslakr** [comment]
It seems like `ASCIIMathML.js` currently uses numerical character references (ie. `&#x03B5;` for `epsilon` = ), but think that that makes it more difficult to find errors. For example in  `ASCIIMathML.js` `varepsilon` is set to `&#x025B;` = ɛ, while it should be `&#x03F5;` = ϵ

But on the other hand, using numerical character references, instead of named entities, might be more compatible with some tools: 

``` sh
$ echo "<title>epsilon</title>&epsilon; &varepsilon; &#x03B5; &#x03F5;"| tidy 
```

``` html
<!DOCTYPE html>
<html>
<head>
<title>epsilon</title>
</head>
<body>
ε &amp;varepsilon; ε ϵ
</body>
</html>
```

**Comment by camoy** [comment]
Yeah, I deliberately selected to change the numerical references in `ASCIIMathML.js` to named entities because it generates more meaningful output. Is there any reason not to generate the actual characters though (I think most editors should be able to handle unicode)?

Additionally, you should definitely file that bug with the tidy project. Their entity table must be out of date!

**Comment by freron** [comment]
My view is that unencoded unicode characters would be best. In other words, only use entities if it turns out that there really are important and frequent practical problems using them. No one should generate non-UTF8 HTML these days (the same goes for emails) and if they do then they can make their own post-processing step to introduce entities.

**Comment by aslakr** [comment]
haha, you already changed everything to UTF-8. 

@freron you might want to test that in your AsciiMath-bundle.

**Comment by freron** [comment]
@aslakr Done. Example:

``````
```math
epsilon=0.01
```
<math display="block"><mi>ε</mi><mo>=</mo><mn>0.01</mn></math>
``````
