### ISSUE TITLE
International characters are not recognized

### ISSUE THREAD

**Issue by milet72** [camoy/amath#16]
I have to use Polish characters (ąćęłńóśźżĄĆĘŁŃÓŚŹŻ) in ASCIIMath expressions. This characters are not recognized as part of identifiers (<mi>) but as operators (<mo>).

**Comment by camoy** [comment]
For the purposes of compatibility with the original, wherein the grammar only considers `[a-zA-Z]` for identifiers I won't add this feature. However, it is very straightforward to add for your particular purposes. Just modify line 406 of `amath.leg` to be:

    ID = [a-zA-Z]|"ą"|"ć"|"ę"|"ł"|"ń"|"ó"|"ś"|"ź"|"ż"|"Ą"|"Ć"|"Ę"|"Ł"|"Ń"|"Ó"|"Ś"|"Ź"|"Ż"

**Comment by milet72** [comment]
----- Original Message -----
